import type { DictionaryEntry, Formality, Lesson, Phrase, SlangLevel } from "@acento/shared";

type TermSeed = {
  term: string;
  meaning: string;
  literalMeaning?: string;
  englishEquivalent: string;
  pronunciation: string;
  formality: Formality;
  slangLevel: SlangLevel;
  usageNotes: string;
  culturalNotes: string;
  commonlyUsedBy: string[];
  safeContexts: string[];
  riskyContexts: string[];
  exampleSentence: string;
  standardSpanishEquivalent: string;
  englishTranslation: string;
  relatedPhrases: string[];
};

const termSeeds: TermSeed[] = [
  {
    term: "qué lo qué",
    meaning: "A casual Dominican greeting similar to what’s up.",
    englishEquivalent: "what’s up",
    pronunciation: "keh lo keh",
    formality: "casual",
    slangLevel: "medium",
    usageNotes:
      "Very casual. Common with friends, younger people, texting, and informal conversation.",
    culturalNotes:
      "It is friendly and recognizable, but it marks the conversation as informal immediately.",
    commonlyUsedBy: ["friends", "younger speakers", "people texting informally"],
    safeContexts: ["close friends", "informal social settings", "casual texting"],
    riskyContexts: ["job interviews", "professors", "elders you do not know", "formal business"],
    exampleSentence: "¿Qué lo qué, mano?",
    standardSpanishEquivalent: "¿Qué tal, amigo?",
    englishTranslation: "What’s up, bro?",
    relatedPhrases: ["klk", "mano", "dime a ve"],
  },
  {
    term: "klk",
    meaning: "Texting abbreviation for qué lo qué.",
    englishEquivalent: "wyd / what’s up",
    pronunciation: "kah-eh-leh-kah or keh lo keh when spoken out",
    formality: "casual",
    slangLevel: "medium",
    usageNotes: "Use in texting and social messaging, not formal writing.",
    culturalNotes: "Common online shorthand; spelling it out in a formal context looks careless.",
    commonlyUsedBy: ["friends", "younger texters", "social media users"],
    safeContexts: ["texts", "DMs", "informal chats"],
    riskyContexts: ["school essays", "work email", "official forms"],
    exampleSentence: "KLK, ¿tamo activo?",
    standardSpanishEquivalent: "¿Qué tal, estamos listos?",
    englishTranslation: "What’s up, are we on?",
    relatedPhrases: ["qué lo qué", "tamo", "ta to"],
  },
  {
    term: "vaina",
    meaning: "A flexible word for thing, situation, problem, stuff, nonsense, or issue.",
    englishEquivalent: "thing / stuff / issue",
    pronunciation: "vai-nah",
    formality: "casual",
    slangLevel: "medium",
    usageNotes:
      "Very common, but context-dependent. Tone controls whether it feels neutral or crude.",
    culturalNotes: "Useful, but learners should avoid overusing it before they understand context.",
    commonlyUsedBy: ["many Dominican speakers in casual conversation"],
    safeContexts: ["friends", "informal explanations", "casual frustration"],
    riskyContexts: ["formal meetings", "customer service as the employee", "academic writing"],
    exampleSentence: "Esa vaina está rara.",
    standardSpanishEquivalent: "Esa cosa/situación está extraña.",
    englishTranslation: "That thing/situation is weird.",
    relatedPhrases: ["ta to", "jevi"],
  },
  {
    term: "jevi",
    meaning: "Cool, nice, good, or awesome.",
    englishEquivalent: "cool",
    pronunciation: "heh-vee",
    formality: "casual",
    slangLevel: "light",
    usageNotes: "Casual and positive. Usually safe with peers.",
    culturalNotes: "Often describes music, plans, people, places, or experiences.",
    commonlyUsedBy: ["friends", "younger speakers", "casual speakers"],
    safeContexts: ["music", "plans", "compliments among peers"],
    riskyContexts: ["formal reports", "serious complaints"],
    exampleSentence: "Esa canción está jevi.",
    standardSpanishEquivalent: "Esa canción está buena.",
    englishTranslation: "That song is cool.",
    relatedPhrases: ["coro", "ta to"],
  },
  {
    term: "coro",
    meaning: "A hangout, group vibe, party, fun gathering, or social plan.",
    englishEquivalent: "hangout",
    pronunciation: "koh-roh",
    formality: "casual",
    slangLevel: "light",
    usageNotes: "Casual social settings. It can mean the plan, the group, or the vibe.",
    culturalNotes: "A social word; it sounds natural when talking about friends and plans.",
    commonlyUsedBy: ["friends", "students", "social groups"],
    safeContexts: ["weekend plans", "music", "friends"],
    riskyContexts: ["formal invitations", "professional scheduling"],
    exampleSentence: "Vamos a hacer un coro esta noche.",
    standardSpanishEquivalent: "Vamos a reunirnos/salir esta noche.",
    englishTranslation: "We’re going to hang out tonight.",
    relatedPhrases: ["jevi", "ta to"],
  },
  {
    term: "tigre",
    meaning: "A street-smart guy, hustler, clever person, or sometimes player depending on tone.",
    englishEquivalent: "street-smart guy",
    pronunciation: "tee-greh",
    formality: "risky",
    slangLevel: "medium",
    usageNotes: "Can be playful or negative. Relationship and tone matter.",
    culturalNotes: "Do not call someone this unless you understand the relationship and tone.",
    commonlyUsedBy: ["casual speakers", "friends", "people describing street smarts"],
    safeContexts: ["describing a clever person with trusted friends"],
    riskyContexts: ["calling a stranger this", "professional contexts", "serious conflict"],
    exampleSentence: "Ese tipo es un tigre.",
    standardSpanishEquivalent: "Ese hombre es muy astuto.",
    englishTranslation: "That guy is street-smart.",
    relatedPhrases: ["loco", "mano"],
  },
  {
    term: "chin",
    meaning: "A little bit.",
    englishEquivalent: "a little",
    pronunciation: "cheen",
    formality: "casual",
    slangLevel: "light",
    usageNotes: "Common and safe in casual speech.",
    culturalNotes: "A practical everyday Dominican word, especially with food and amounts.",
    commonlyUsedBy: ["all ages in casual Dominican speech"],
    safeContexts: ["ordering food", "asking for small amounts", "family settings"],
    riskyContexts: ["formal documents", "technical measurements"],
    exampleSentence: "Dame un chin de agua.",
    standardSpanishEquivalent: "Dame un poco de agua.",
    englishTranslation: "Give me a little water.",
    relatedPhrases: ["un poco", "solo un chin"],
  },
  {
    term: "guagua",
    meaning: "Bus or van/public transport in Dominican Spanish.",
    englishEquivalent: "bus",
    pronunciation: "gwah-gwah",
    formality: "neutral",
    slangLevel: "none",
    usageNotes: "Common everyday word in the Dominican Republic.",
    culturalNotes: "In some countries guagua can mean something else, so country context matters.",
    commonlyUsedBy: ["commuters", "travelers", "everyday speakers"],
    safeContexts: ["transportation", "directions", "travel"],
    riskyContexts: ["assuming it means bus in every country"],
    exampleSentence: "Voy en guagua.",
    standardSpanishEquivalent: "Voy en autobús.",
    englishTranslation: "I’m going by bus.",
    relatedPhrases: ["concho", "taxi"],
  },
  {
    term: "concho",
    meaning: "Shared public car or route taxi.",
    englishEquivalent: "shared taxi",
    pronunciation: "kohn-choh",
    formality: "neutral",
    slangLevel: "none",
    usageNotes: "Dominican transportation context.",
    culturalNotes: "Useful for getting around, but route systems can be confusing for visitors.",
    commonlyUsedBy: ["commuters", "drivers", "travelers"],
    safeContexts: ["transportation", "directions", "asking locals"],
    riskyContexts: ["using it outside Dominican transportation context without explanation"],
    exampleSentence: "Voy a coger un concho.",
    standardSpanishEquivalent: "Voy a tomar un taxi compartido.",
    englishTranslation: "I’m going to take a shared taxi.",
    relatedPhrases: ["guagua", "taxi"],
  },
  {
    term: "dime a ve",
    meaning: "A casual phrase similar to tell me, what’s up, or let me hear it.",
    englishEquivalent: "tell me / what’s up",
    pronunciation: "dee-meh ah veh",
    formality: "casual",
    slangLevel: "light",
    usageNotes: "Casual conversation. Often opens a story or asks what happened.",
    culturalNotes: "It invites someone to talk; tone can be warm, curious, or impatient.",
    commonlyUsedBy: ["friends", "family", "casual speakers"],
    safeContexts: ["friends", "informal updates", "casual storytelling"],
    riskyContexts: ["formal meetings", "speaking to authority figures"],
    exampleSentence: "Dime a ve, ¿qué pasó?",
    standardSpanishEquivalent: "Dime, ¿qué pasó?",
    englishTranslation: "Tell me, what happened?",
    relatedPhrases: ["qué lo qué", "mano"],
  },
  {
    term: "ta to",
    meaning: "It’s all good, okay, agreed, or fine.",
    englishEquivalent: "all good",
    pronunciation: "tah toh",
    formality: "casual",
    slangLevel: "medium",
    usageNotes: "Very casual. Do not use in formal writing.",
    culturalNotes: "Shortened speech is common in casual conversation but not universal or formal.",
    commonlyUsedBy: ["friends", "texters", "casual speakers"],
    safeContexts: ["friends", "quick plans", "texting"],
    riskyContexts: ["professional emails", "school writing", "formal commitments"],
    exampleSentence: "Ta to, nos vemos ahora.",
    standardSpanishEquivalent: "Está bien, nos vemos pronto.",
    englishTranslation: "All good, see you soon.",
    relatedPhrases: ["klk", "coro"],
  },
  {
    term: "mano",
    meaning: "Bro, man, buddy. Shortened from hermano.",
    literalMeaning: "hand; shortened from hermano in this usage",
    englishEquivalent: "bro",
    pronunciation: "mah-noh",
    formality: "casual",
    slangLevel: "light",
    usageNotes: "Very casual and friendly.",
    culturalNotes: "Use only where a friendly casual address fits.",
    commonlyUsedBy: ["male friends", "close peers", "casual speakers"],
    safeContexts: ["friends", "warm thanks", "informal greetings"],
    riskyContexts: ["elders you do not know", "formal service", "professional meetings"],
    exampleSentence: "Gracias, mano.",
    standardSpanishEquivalent: "Gracias, amigo.",
    englishTranslation: "Thanks, bro.",
    relatedPhrases: ["qué lo qué", "loco"],
  },
  {
    term: "loco",
    meaning: "Dude/man in casual Dominican speech; literally crazy.",
    literalMeaning: "crazy",
    englishEquivalent: "dude",
    pronunciation: "loh-koh",
    formality: "risky",
    slangLevel: "medium",
    usageNotes: "Tone matters. It can be friendly or disrespectful.",
    culturalNotes: "Do not use with strangers until you understand the relationship.",
    commonlyUsedBy: ["friends", "close peers", "casual speakers"],
    safeContexts: ["close friends", "playful tone"],
    riskyContexts: ["strangers", "conflict", "work", "elders"],
    exampleSentence: "Loco, ven acá.",
    standardSpanishEquivalent: "Amigo, ven aquí.",
    englishTranslation: "Dude, come here.",
    relatedPhrases: ["mano", "tigre"],
  },
  {
    term: "mi amor",
    meaning:
      "My love. Can be romantic, affectionate, customer-service warmth, or culturally casual depending on speaker and context.",
    literalMeaning: "my love",
    englishEquivalent: "dear / love",
    pronunciation: "mee ah-mor",
    formality: "intimate",
    slangLevel: "none",
    usageNotes:
      "Do not teach this only as romantic. It can be warm from vendors, older women, family, partners, or close acquaintances.",
    culturalNotes:
      "Using it toward strangers, coworkers, service workers, or women you do not know can sound flirtatious, invasive, or disrespectful.",
    commonlyUsedBy: [
      "partners",
      "family",
      "some vendors",
      "older women in warm service interactions",
    ],
    safeContexts: [
      "partner",
      "family",
      "someone already affectionate with you",
      "vendor using it to you",
    ],
    riskyContexts: ["strangers", "coworkers", "service workers", "women you do not know"],
    exampleSentence: "¿Qué tú quieres, mi amor?",
    standardSpanishEquivalent: "¿Qué quieres?",
    englishTranslation: "What would you like, dear?",
    relatedPhrases: ["cariño", "amor"],
  },
];

export const dictionary: DictionaryEntry[] = termSeeds.map((entry) => ({
  id: entry.term
    .normalize("NFD")
    .replace(/\p{Diacritic}/gu, "")
    .replace(/\s+/g, "-"),
  region: "Dominican Republic",
  difficulty: "beginner",
  audio: { slow: "audio://placeholder/slow", native: "audio://placeholder/native" },
  ...entry,
}));

const phrase = (
  lessonId: string,
  id: string,
  english: string,
  standardSpanish: string,
  dominican: string,
  context: string,
  culturalNote: string,
  safeToUseWith: string[],
  avoidWith: string[],
  tags: string[],
  formality: Formality = "casual",
  slangLevel: SlangLevel = "light",
  pronunciation?: string,
): Phrase => ({
  id,
  lessonId,
  english,
  standardSpanish,
  regionalSpanish: [{ dialect: "dominican", text: dominican, pronunciation }],
  formality,
  slangLevel,
  context,
  culturalNote,
  safeToUseWith,
  avoidWith,
  examples: [
    {
      speakerA: dominican,
      speakerB: "Ta to.",
      english: `${english}. All good.`,
    },
  ],
  tags,
  audio: { slow: "audio://placeholder/slow", native: "audio://placeholder/native" },
});

const commonSafe = ["friends", "family", "casual peers"];
const formalAvoid = ["job interviews", "formal business", "elders you do not know"];

export const lessons: Lesson[] = [
  {
    id: "greetings",
    title: "Greetings",
    description: "Learn how to greet people without sounding robotic or too familiar.",
    level: "beginner",
    estimatedMinutes: 8,
    category: "Greetings",
    dialectFocus: ["standard", "dominican"],
    cultureNote:
      "Dominican greetings vary by age, relationship, place, and tone. Start neutral, then mirror the level of warmth you receive.",
    streetVsStandard: {
      standard: "¿Cómo estás?",
      street: "¿Qué lo qué? / KLK",
      guidance:
        "Use standard greetings with strangers, teachers, coworkers, and elders. Use KLK only with friends or informal texting.",
    },
    phrases: [
      phrase(
        "greetings",
        "greet-hola",
        "Hello",
        "Hola",
        "Hola",
        "Neutral and safe anywhere.",
        "Simple greetings are never wrong.",
        ["everyone"],
        [],
        ["hola"],
        "neutral",
        "none",
      ),
      phrase(
        "greetings",
        "greet-como-estas",
        "How are you?",
        "¿Cómo estás?",
        "¿Cómo tú ta?",
        "Casual spoken Dominican drops sounds.",
        "Understand it before using it heavily.",
        commonSafe,
        formalAvoid,
        ["how-are-you"],
        "casual",
        "light",
        "koh-moh too tah",
      ),
      phrase(
        "greetings",
        "greet-que-tal",
        "How’s it going?",
        "¿Qué tal?",
        "¿Qué tal?",
        "Neutral greeting for most settings.",
        "A strong default when unsure.",
        ["friends", "coworkers", "teachers"],
        [],
        ["neutral"],
        "neutral",
        "none",
      ),
      phrase(
        "greetings",
        "greet-que-lo-que",
        "What’s up?",
        "¿Qué tal?",
        "¿Qué lo qué?",
        "Informal Dominican greeting.",
        "Not for formal situations or elders you do not know.",
        commonSafe,
        formalAvoid,
        ["qué lo qué"],
        "casual",
        "medium",
        "keh lo keh",
      ),
      phrase(
        "greetings",
        "greet-dime-a-ve",
        "Tell me what’s up",
        "Dime, ¿qué pasó?",
        "Dime a ve, ¿qué pasó?",
        "Casual prompt for news or a story.",
        "Tone can be curious or impatient.",
        commonSafe,
        formalAvoid,
        ["dime a ve"],
        "casual",
        "light",
      ),
    ],
    flashcards: [
      {
        front: "¿Qué lo qué?",
        back: "Casual Dominican: what’s up?",
        hint: "Friends, not interviews.",
      },
      { front: "KLK", back: "Texting shorthand for ¿qué lo qué?" },
      { front: "Ta to", back: "All good / okay." },
      { front: "¿Qué tal?", back: "Neutral: how’s it going?" },
      { front: "¿Cómo estás?", back: "Standard: how are you?" },
    ],
    dialogue: [
      { speaker: "A", text: "Hola, ¿qué tal?", translation: "Hi, how’s it going?" },
      { speaker: "B", text: "Bien, gracias. ¿Y tú?", translation: "Good, thanks. And you?" },
      { speaker: "A", text: "Ta to.", translation: "All good." },
    ],
    practicePrompts: ["Greet a teacher.", "Text a close friend.", "Greet an elder respectfully."],
    quickQuiz: {
      prompt: "Which greeting is safest for a job interview?",
      options: ["KLK", "¿Qué lo qué?", "Buenos días"],
      answer: "Buenos días",
      explanation: "Formal contexts need standard Spanish.",
    },
    relatedDictionaryTerms: ["que-lo-que", "klk", "dime-a-ve", "ta-to", "mano"],
  },
  {
    id: "introductions",
    title: "Introductions",
    description: "Introduce yourself clearly and respectfully.",
    level: "beginner",
    estimatedMinutes: 7,
    category: "Introductions",
    dialectFocus: ["standard", "dominican"],
    cultureNote:
      "For first meetings, clean standard Spanish is usually better than slang. Warmth can come after rapport.",
    streetVsStandard: {
      standard: "Mucho gusto.",
      street: "Un placer, mano.",
      guidance: "Keep introductions mostly standard until you know the relationship.",
    },
    phrases: [
      phrase(
        "introductions",
        "intro-me-llamo",
        "My name is...",
        "Me llamo...",
        "Me llamo...",
        "Safe in every setting.",
        "Names are best kept clear.",
        ["everyone"],
        [],
        ["name"],
        "neutral",
        "none",
      ),
      phrase(
        "introductions",
        "intro-soy-de",
        "I am from...",
        "Soy de...",
        "Soy de...",
        "Use for country or city.",
        "Nationality can invite friendly conversation.",
        ["everyone"],
        [],
        ["origin"],
        "neutral",
        "none",
      ),
      phrase(
        "introductions",
        "intro-vivo-en",
        "I live in...",
        "Vivo en...",
        "Vivo en...",
        "Use for current city.",
        "Share only what feels safe.",
        ["everyone"],
        [],
        ["home"],
        "neutral",
        "none",
      ),
      phrase(
        "introductions",
        "intro-mucho-gusto",
        "Nice to meet you",
        "Mucho gusto",
        "Mucho gusto",
        "Polite first meeting.",
        "Reliable with elders and coworkers.",
        ["everyone"],
        [],
        ["polite"],
        "neutral",
        "none",
      ),
      phrase(
        "introductions",
        "intro-aprendiendo",
        "I am learning Spanish",
        "Estoy aprendiendo español",
        "Toy aprendiendo español",
        "Casual speech may shorten estoy to toy.",
        "Do not write toy in formal work.",
        commonSafe,
        ["formal writing"],
        ["learning"],
        "casual",
        "light",
      ),
    ],
    flashcards: [
      { front: "Me llamo...", back: "My name is..." },
      { front: "Soy de...", back: "I am from..." },
      { front: "Vivo en...", back: "I live in..." },
      { front: "Mucho gusto", back: "Nice to meet you" },
      { front: "Estoy aprendiendo español", back: "I am learning Spanish" },
    ],
    dialogue: [
      { speaker: "A", text: "Hola, me llamo Maya.", translation: "Hi, my name is Maya." },
      {
        speaker: "B",
        text: "Mucho gusto. ¿De dónde eres?",
        translation: "Nice to meet you. Where are you from?",
      },
      {
        speaker: "A",
        text: "Soy americana y estoy aprendiendo español.",
        translation: "I’m American and I’m learning Spanish.",
      },
    ],
    practicePrompts: [
      "Introduce yourself to a classmate.",
      "Tell someone where you live.",
      "Say you are learning Spanish.",
    ],
    quickQuiz: {
      prompt: "Which version belongs in a work email?",
      options: ["Toy aprendiendo", "Estoy aprendiendo español", "KLK"],
      answer: "Estoy aprendiendo español",
      explanation: "Use full standard forms in formal writing.",
    },
    relatedDictionaryTerms: ["mano"],
  },
  {
    id: "ordering-food",
    title: "Ordering Food",
    description: "Order politely and understand warm service language.",
    level: "beginner",
    estimatedMinutes: 9,
    category: "Restaurants",
    dialectFocus: ["standard", "dominican"],
    cultureNote:
      "Polite ordering matters. Direct phrases can be acceptable, but adding por favor softens the tone.",
    streetVsStandard: {
      standard: "Me da un poco de agua, por favor.",
      street: "Dame un chin de agua.",
      guidance:
        "Use me da and por favor with staff. Use dame with people you know or in very casual settings.",
    },
    phrases: [
      phrase(
        "ordering-food",
        "food-quiero",
        "I want...",
        "Quiero...",
        "Quiero...",
        "Basic but can sound direct.",
        "Add por favor to sound warmer.",
        ["restaurants"],
        [],
        ["order"],
        "neutral",
        "none",
      ),
      phrase(
        "ordering-food",
        "food-me-da",
        "Could you give me...",
        "¿Me da...?",
        "¿Me da...?",
        "Polite ordering structure.",
        "Good default with staff.",
        ["servers", "vendors"],
        [],
        ["polite"],
        "neutral",
        "none",
      ),
      phrase(
        "ordering-food",
        "food-cuanto",
        "How much does it cost?",
        "¿Cuánto cuesta?",
        "¿Cuánto es?",
        "Common price question.",
        "Both are practical.",
        ["vendors", "servers"],
        [],
        ["price"],
        "neutral",
        "none",
      ),
      phrase(
        "ordering-food",
        "food-chin",
        "A little bit",
        "Un poco",
        "Un chin",
        "Common Dominican amount word.",
        "Safe casually, not technical.",
        commonSafe.concat(["food vendors"]),
        ["formal measurement"],
        ["chin"],
        "casual",
        "light",
      ),
      phrase(
        "ordering-food",
        "food-mi-amor",
        "Dear / love in service context",
        "Señor/señora",
        "Mi amor",
        "May be used warmly by some vendors.",
        "Do not assume you should say it to staff.",
        ["when said to you"],
        ["strangers", "coworkers"],
        ["mi amor"],
        "intimate",
        "none",
      ),
    ],
    flashcards: [
      { front: "Me da...", back: "Could you give me..." },
      { front: "Un chin", back: "A little bit" },
      { front: "Mangú", back: "Mashed plantain dish" },
      { front: "Jugo", back: "Juice" },
      { front: "Café", back: "Coffee" },
    ],
    dialogue: [
      {
        speaker: "Cliente",
        text: "¿Me da mangú con pollo, por favor?",
        translation: "Could you give me mangú with chicken, please?",
      },
      {
        speaker: "Servidor",
        text: "Claro, mi amor. ¿Algo de tomar?",
        translation: "Of course, dear. Anything to drink?",
      },
      { speaker: "Cliente", text: "Un jugo, por favor.", translation: "A juice, please." },
    ],
    practicePrompts: ["Order coffee politely.", "Ask the price.", "Ask for a little water."],
    quickQuiz: {
      prompt: "Which is the most polite way to order?",
      options: ["Dame pollo", "¿Me da pollo, por favor?", "KLK pollo"],
      answer: "¿Me da pollo, por favor?",
      explanation: "Me da plus por favor is polite and natural.",
    },
    relatedDictionaryTerms: ["chin", "mi-amor"],
  },
  {
    id: "family",
    title: "Family",
    description: "Talk about family with warmth and clarity.",
    level: "beginner",
    estimatedMinutes: 7,
    category: "Family",
    dialectFocus: ["standard", "dominican"],
    cultureNote:
      "Family language is often warm and affectionate, but intimacy depends on relationship.",
    streetVsStandard: {
      standard: "Mi familia",
      street: "Mi gente",
      guidance: "Mi gente can mean my people, family, or close circle in warm informal speech.",
    },
    phrases: [
      phrase(
        "family",
        "family-madre",
        "Mother",
        "Madre",
        "Mamá",
        "Mamá is warmer and common.",
        "Madre can sound formal depending on tone.",
        ["family", "general conversation"],
        [],
        ["family"],
        "neutral",
        "none",
      ),
      phrase(
        "family",
        "family-padre",
        "Father",
        "Padre",
        "Papá",
        "Papá is warmer and common.",
        "Use padre in formal forms.",
        ["family"],
        [],
        ["family"],
        "neutral",
        "none",
      ),
      phrase(
        "family",
        "family-hermano",
        "Brother",
        "Hermano",
        "Hermano / mano",
        "Mano is a casual address from hermano.",
        "Mano is not for formal introductions.",
        commonSafe,
        formalAvoid,
        ["mano"],
        "casual",
        "light",
      ),
      phrase(
        "family",
        "family-primo",
        "Cousin",
        "Primo",
        "Primo",
        "Common family word.",
        "Cousins can be socially close.",
        ["everyone"],
        [],
        ["family"],
        "neutral",
        "none",
      ),
      phrase(
        "family",
        "family-mi-gente",
        "My people / my family",
        "Mi familia",
        "Mi gente",
        "Warm informal way to refer to your people.",
        "Not a legal or formal substitute for family.",
        commonSafe,
        ["official forms"],
        ["family"],
        "casual",
        "light",
      ),
    ],
    flashcards: [
      { front: "Madre", back: "Mother" },
      { front: "Mamá", back: "Mom" },
      { front: "Hermano", back: "Brother" },
      { front: "Primo", back: "Cousin" },
      { front: "Mi gente", back: "My people / my close circle" },
    ],
    dialogue: [
      { speaker: "A", text: "¿Tienes familia aquí?", translation: "Do you have family here?" },
      {
        speaker: "B",
        text: "Sí, mi mamá y mi hermano viven aquí.",
        translation: "Yes, my mom and my brother live here.",
      },
      { speaker: "A", text: "Qué bueno.", translation: "That’s great." },
    ],
    practicePrompts: [
      "Say who is in your family.",
      "Ask about someone’s cousin.",
      "Use mi gente casually.",
    ],
    quickQuiz: {
      prompt: "What does mi gente usually mean in warm casual speech?",
      options: ["My office", "My people / close circle", "My car"],
      answer: "My people / close circle",
      explanation: "It can refer to family, friends, or your group.",
    },
    relatedDictionaryTerms: ["mano", "mi-amor"],
  },
  {
    id: "flirting-respectfully",
    title: "Flirting Respectfully",
    description: "Express interest without pressure, entitlement, or disrespect.",
    level: "elementary",
    estimatedMinutes: 10,
    category: "Dating",
    dialectFocus: ["standard", "dominican"],
    cultureNote:
      "Respect matters more than sounding local. If someone is not interested, stop. Do not pressure, follow, or comment on bodies.",
    streetVsStandard: {
      standard: "Me gusta hablar contigo.",
      street: "Tú me caes bien.",
      guidance: "Choose warm, low-pressure phrases. Avoid overly intimate terms with strangers.",
    },
    phrases: [
      phrase(
        "flirting-respectfully",
        "flirt-look-nice",
        "You look nice",
        "Te ves muy bien",
        "Te ves muy bien",
        "Respectful compliment.",
        "Avoid sexual comments or repeated comments after discomfort.",
        ["dates", "someone receptive"],
        ["strangers who seem uncomfortable"],
        ["respect"],
        "neutral",
        "none",
      ),
      phrase(
        "flirting-respectfully",
        "flirt-take-out",
        "Can I take you out?",
        "¿Te puedo invitar a salir?",
        "¿Te puedo invitar a salir?",
        "Clear and respectful invitation.",
        "No means no; do not negotiate.",
        ["someone you already talk with"],
        ["work pressure", "service workers"],
        ["consent"],
        "neutral",
        "none",
      ),
      phrase(
        "flirting-respectfully",
        "flirt-number",
        "Can I have your number?",
        "¿Me das tu número?",
        "¿Me das tu número?",
        "Ask once and accept the answer.",
        "Do not ask repeatedly.",
        ["mutual interest"],
        ["trapped contexts"],
        ["consent"],
        "neutral",
        "none",
      ),
      phrase(
        "flirting-respectfully",
        "flirt-talking",
        "I like talking to you",
        "Me gusta hablar contigo",
        "Me gusta hablar contigo",
        "Low-pressure affection.",
        "Good because it focuses on connection.",
        ["dates", "friendly conversation"],
        [],
        ["respect"],
        "neutral",
        "none",
      ),
      phrase(
        "flirting-respectfully",
        "flirt-mi-amor",
        "My love / dear",
        "Cariño",
        "Mi amor",
        "Can be intimate or culturally warm.",
        "Risky toward strangers and can sound invasive.",
        ["partners", "someone already affectionate"],
        ["strangers", "coworkers", "service workers"],
        ["mi amor"],
        "intimate",
        "none",
      ),
    ],
    flashcards: [
      { front: "Te ves muy bien", back: "You look nice" },
      { front: "¿Te puedo invitar a salir?", back: "Can I take you out?" },
      { front: "Me gusta hablar contigo", back: "I like talking to you" },
      { front: "Consent", back: "Accept no immediately" },
      { front: "Mi amor", back: "Context-dependent and risky with strangers" },
    ],
    dialogue: [
      { speaker: "A", text: "Me gusta hablar contigo.", translation: "I like talking to you." },
      { speaker: "B", text: "Gracias, yo también.", translation: "Thanks, me too." },
      {
        speaker: "A",
        text: "¿Te puedo invitar a un café?",
        translation: "Can I take you out for coffee?",
      },
    ],
    practicePrompts: [
      "Give a respectful compliment.",
      "Ask for a date with no pressure.",
      "Explain when not to use mi amor.",
    ],
    quickQuiz: {
      prompt: "What should you do if someone says no?",
      options: ["Ask again", "Accept it and stop", "Use a stronger phrase"],
      answer: "Accept it and stop",
      explanation: "Respect and consent are non-negotiable.",
    },
    relatedDictionaryTerms: ["mi-amor"],
  },
  {
    id: "texting",
    title: "Texting",
    description: "Understand casual Dominican texting without using it in the wrong place.",
    level: "elementary",
    estimatedMinutes: 8,
    category: "Texting",
    dialectFocus: ["standard", "dominican"],
    cultureNote:
      "Texting forms are not spelling mistakes in context, but they are not appropriate for school essays, work emails, or formal writing.",
    streetVsStandard: {
      standard: "Estoy aquí. Estamos listos para vernos.",
      street: "Toy aquí. Tamo ready pa vernos.",
      guidance: "Use texting forms only with people who already text that way with you.",
    },
    phrases: [
      phrase(
        "texting",
        "text-klk",
        "What’s up?",
        "¿Qué tal?",
        "KLK",
        "Text abbreviation.",
        "Very informal.",
        ["friends", "DMs"],
        ["work", "school writing"],
        ["klk"],
        "casual",
        "medium",
      ),
      phrase(
        "texting",
        "text-toy",
        "I am here",
        "Estoy aquí",
        "Toy aquí",
        "Shortened estoy.",
        "Not for formal writing.",
        ["texts"],
        ["essays", "emails"],
        ["toy"],
        "casual",
        "light",
      ),
      phrase(
        "texting",
        "text-tamo",
        "We are",
        "Estamos",
        "Tamo",
        "Shortened estamos.",
        "Common in casual texting.",
        ["friends"],
        ["formal writing"],
        ["tamo"],
        "casual",
        "light",
      ),
      phrase(
        "texting",
        "text-pa",
        "For / to",
        "Para",
        "Pa’",
        "Shortened para.",
        "The apostrophe marks dropped sound.",
        ["texts", "lyrics"],
        ["formal writing"],
        ["pa"],
        "casual",
        "light",
      ),
      phrase(
        "texting",
        "text-ta-to",
        "All good",
        "Está bien",
        "Ta to",
        "Agreement in casual texting.",
        "Do not use with professors or bosses.",
        ["friends"],
        ["professors", "bosses"],
        ["ta to"],
        "casual",
        "medium",
      ),
    ],
    flashcards: [
      { front: "KLK", back: "What’s up?" },
      { front: "Toy", back: "Estoy" },
      { front: "Tamo", back: "Estamos" },
      { front: "Pa’", back: "Para" },
      { front: "Ta to", back: "All good" },
    ],
    dialogue: [
      { speaker: "A", text: "KLK, ¿toy tarde?", translation: "What’s up, am I late?" },
      { speaker: "B", text: "No, ta to.", translation: "No, all good." },
      { speaker: "A", text: "Tamo ahí ahora.", translation: "We’ll be there soon." },
    ],
    practicePrompts: [
      "Rewrite a text into standard Spanish.",
      "Identify which forms are texting-only.",
      "Respond casually to KLK.",
    ],
    quickQuiz: {
      prompt: "Where should you avoid writing toy aquí?",
      options: ["A close friend text", "A school essay", "A group chat"],
      answer: "A school essay",
      explanation: "Use estoy aquí in formal writing.",
    },
    relatedDictionaryTerms: ["klk", "ta-to"],
  },
  {
    id: "travel",
    title: "Travel",
    description: "Navigate transportation and directions in the Dominican Republic.",
    level: "beginner",
    estimatedMinutes: 9,
    category: "Travel",
    dialectFocus: ["standard", "dominican"],
    cultureNote:
      "Transportation words vary by country. In the Dominican Republic, guagua and concho are everyday words.",
    streetVsStandard: {
      standard: "Voy en autobús.",
      street: "Voy en guagua.",
      guidance:
        "Use Dominican transport words in Dominican contexts. Do not assume the same meaning everywhere.",
    },
    phrases: [
      phrase(
        "travel",
        "travel-guagua",
        "I’m going by bus",
        "Voy en autobús",
        "Voy en guagua",
        "Dominican bus/van term.",
        "Country context matters.",
        ["Dominican transportation"],
        ["other countries without context"],
        ["guagua"],
        "neutral",
        "none",
      ),
      phrase(
        "travel",
        "travel-concho",
        "I’m taking a shared taxi",
        "Voy a tomar un taxi compartido",
        "Voy a coger un concho",
        "Route taxi context.",
        "Useful but ask locals how routes work.",
        ["Dominican transportation"],
        ["formal travel writing"],
        ["concho"],
        "neutral",
        "none",
      ),
      phrase(
        "travel",
        "travel-airport",
        "Airport",
        "Aeropuerto",
        "Aeropuerto",
        "Standard and safe.",
        "Clear in all countries.",
        ["everyone"],
        [],
        ["airport"],
        "neutral",
        "none",
      ),
      phrase(
        "travel",
        "travel-left",
        "Left",
        "Izquierda",
        "Izquierda",
        "Direction word.",
        "Useful in taxis and walking.",
        ["drivers", "travel"],
        [],
        ["directions"],
        "neutral",
        "none",
      ),
      phrase(
        "travel",
        "travel-cuanto-falta",
        "How much farther?",
        "¿Cuánto falta?",
        "¿Cuánto falta?",
        "Ask about remaining time/distance.",
        "Common and practical.",
        ["drivers", "friends"],
        [],
        ["directions"],
        "neutral",
        "none",
      ),
    ],
    flashcards: [
      { front: "Guagua", back: "Bus/van in Dominican Spanish" },
      { front: "Concho", back: "Shared public car / route taxi" },
      { front: "Aeropuerto", back: "Airport" },
      { front: "Izquierda", back: "Left" },
      { front: "¿Cuánto falta?", back: "How much farther?" },
    ],
    dialogue: [
      {
        speaker: "A",
        text: "¿Voy en guagua o en concho?",
        translation: "Should I go by bus or shared taxi?",
      },
      { speaker: "B", text: "Mejor en concho.", translation: "Better by shared taxi." },
      { speaker: "A", text: "¿Cuánto falta?", translation: "How much farther?" },
    ],
    practicePrompts: [
      "Ask for the hotel.",
      "Say you are taking a guagua.",
      "Ask how much farther.",
    ],
    quickQuiz: {
      prompt: "In Dominican Spanish, what is a concho?",
      options: ["A beach", "A shared public car", "A hotel"],
      answer: "A shared public car",
      explanation: "Concho is a Dominican transportation term.",
    },
    relatedDictionaryTerms: ["guagua", "concho"],
  },
  {
    id: "work",
    title: "Work",
    description: "Code-switch between casual Dominican Spanish and professional Spanish.",
    level: "elementary",
    estimatedMinutes: 8,
    category: "Business",
    dialectFocus: ["standard", "dominican"],
    cultureNote:
      "Professional Spanish often requires fuller forms and less slang, even if coworkers speak casually at lunch.",
    streetVsStandard: {
      standard: "Estoy ocupado. Tengo una reunión.",
      street: "Toy ocupado. Tengo una reunión.",
      guidance: "Use standard forms in meetings, email, interviews, and with new coworkers.",
    },
    phrases: [
      phrase(
        "work",
        "work-trabajo",
        "Work",
        "Trabajo",
        "Trabajo",
        "Core work word.",
        "Safe everywhere.",
        ["everyone"],
        [],
        ["work"],
        "neutral",
        "none",
      ),
      phrase(
        "work",
        "work-reunion",
        "Meeting",
        "Reunión",
        "Reunión",
        "Professional word.",
        "Use in scheduling.",
        ["coworkers"],
        [],
        ["meeting"],
        "neutral",
        "none",
      ),
      phrase(
        "work",
        "work-jefe",
        "Boss",
        "Jefe",
        "Jefe",
        "Common word for boss.",
        "Tone can sound blunt; use title/name when appropriate.",
        ["coworkers"],
        ["formal complaints"],
        ["boss"],
        "neutral",
        "none",
      ),
      phrase(
        "work",
        "work-ocupado",
        "I’m busy",
        "Estoy ocupado",
        "Toy ocupado",
        "Casual speech may shorten estoy.",
        "Use full form at work.",
        ["friends at work"],
        ["bosses", "formal meetings"],
        ["code-switching"],
        "casual",
        "light",
      ),
      phrase(
        "work",
        "work-avoid-slang",
        "Good morning",
        "Buenos días",
        "Buenos días",
        "Formal greeting.",
        "Best for interviews and meetings.",
        ["everyone"],
        [],
        ["formal"],
        "formal",
        "none",
      ),
    ],
    flashcards: [
      { front: "Trabajo", back: "Work" },
      { front: "Reunión", back: "Meeting" },
      { front: "Jefe", back: "Boss" },
      { front: "Estoy ocupado", back: "I’m busy" },
      { front: "Buenos días", back: "Good morning" },
    ],
    dialogue: [
      {
        speaker: "A",
        text: "Buenos días. Tengo una reunión.",
        translation: "Good morning. I have a meeting.",
      },
      {
        speaker: "B",
        text: "Claro, hablamos después.",
        translation: "Of course, we’ll talk later.",
      },
      { speaker: "A", text: "Gracias.", translation: "Thanks." },
    ],
    practicePrompts: [
      "Greet a boss.",
      "Tell a coworker you are busy.",
      "Rewrite toy ocupado for an email.",
    ],
    quickQuiz: {
      prompt: "Which is best for a work email?",
      options: ["Toy ocupado", "Estoy ocupado", "Ta to"],
      answer: "Estoy ocupado",
      explanation: "Professional writing needs standard forms.",
    },
    relatedDictionaryTerms: ["ta-to"],
  },
  {
    id: "barber-shop",
    title: "Barber Shop",
    description: "Ask for a haircut clearly in Dominican and Caribbean contexts.",
    level: "elementary",
    estimatedMinutes: 8,
    category: "Barber Shop",
    dialectFocus: ["standard", "dominican"],
    cultureNote: "Barber vocabulary is practical and specific. Bring a photo if precision matters.",
    streetVsStandard: {
      standard: "Solo un poco, no muy corto.",
      street: "Solo un chin, no muy bajito.",
      guidance: "Un chin and bajito are useful in casual barber settings.",
    },
    phrases: [
      phrase(
        "barber-shop",
        "barber-recorte",
        "Haircut",
        "Corte de pelo",
        "Recorte",
        "Common Dominican/Caribbean barber word.",
        "Useful at the barber shop.",
        ["barbers"],
        [],
        ["barber"],
        "neutral",
        "light",
      ),
      phrase(
        "barber-shop",
        "barber-bajito",
        "Short",
        "Corto",
        "Bajito",
        "Practical haircut length word.",
        "Clarify how short.",
        ["barbers"],
        [],
        ["haircut"],
        "casual",
        "light",
      ),
      phrase(
        "barber-shop",
        "barber-no-muy",
        "Not too short",
        "No muy corto",
        "No muy bajito",
        "Protects against cutting too much.",
        "Say this clearly.",
        ["barbers"],
        [],
        ["haircut"],
        "neutral",
        "light",
      ),
      phrase(
        "barber-shop",
        "barber-barba",
        "The beard",
        "La barba",
        "La barba",
        "Standard and safe.",
        "Use with trimming requests.",
        ["barbers"],
        [],
        ["beard"],
        "neutral",
        "none",
      ),
      phrase(
        "barber-shop",
        "barber-chin",
        "Just a little",
        "Solo un poco",
        "Solo un chin",
        "Small amount request.",
        "Useful but casual.",
        ["barbers", "friends"],
        ["formal contexts"],
        ["chin"],
        "casual",
        "light",
      ),
    ],
    flashcards: [
      { front: "Recorte", back: "Haircut" },
      { front: "Barbería", back: "Barber shop" },
      { front: "No muy bajito", back: "Not too short" },
      { front: "La barba", back: "The beard" },
      { front: "Solo un chin", back: "Just a little" },
    ],
    dialogue: [
      {
        speaker: "Cliente",
        text: "Quiero un recorte, no muy bajito.",
        translation: "I want a haircut, not too short.",
      },
      { speaker: "Barbero", text: "¿Y la barba?", translation: "And the beard?" },
      { speaker: "Cliente", text: "Solo un chin.", translation: "Just a little." },
    ],
    practicePrompts: [
      "Ask for not too short.",
      "Ask the price.",
      "Say only a little on the beard.",
    ],
    quickQuiz: {
      prompt: "What does solo un chin mean at the barber shop?",
      options: ["A lot", "Just a little", "No haircut"],
      answer: "Just a little",
      explanation: "Chin means a little bit.",
    },
    relatedDictionaryTerms: ["chin"],
  },
  {
    id: "common-dominican-expressions",
    title: "Common Dominican Expressions",
    description:
      "The flagship starter lesson for useful Dominican expressions with context and caution.",
    level: "elementary",
    estimatedMinutes: 12,
    category: "Dominican Culture",
    dialectFocus: ["standard", "dominican"],
    cultureNote:
      "Dominican Spanish is not one single speech pattern. Usage varies by region, age, class, relationship, context, and personal style.",
    streetVsStandard: {
      standard: "¿Qué tal, amigo? Está bien.",
      street: "¿Qué lo qué, mano? Ta to.",
      guidance:
        "These expressions are powerful for comprehension, but learners should use them carefully and never as a costume.",
    },
    phrases: [
      phrase(
        "common-dominican-expressions",
        "expr-que-lo-que",
        "What’s up, bro?",
        "¿Qué tal, amigo?",
        "¿Qué lo qué, mano?",
        "Very casual greeting.",
        "Use with friends, not formal contexts.",
        commonSafe,
        formalAvoid,
        ["qué lo qué", "mano"],
        "casual",
        "medium",
      ),
      phrase(
        "common-dominican-expressions",
        "expr-vaina",
        "That thing is weird",
        "Esa cosa está extraña",
        "Esa vaina está rara",
        "Flexible word for thing/situation.",
        "Too informal for formal settings.",
        commonSafe,
        formalAvoid,
        ["vaina"],
        "casual",
        "medium",
      ),
      phrase(
        "common-dominican-expressions",
        "expr-jevi",
        "That song is cool",
        "Esa canción está buena",
        "Esa canción está jevi",
        "Positive casual description.",
        "Safe with peers.",
        commonSafe,
        ["formal reports"],
        ["jevi"],
        "casual",
        "light",
      ),
      phrase(
        "common-dominican-expressions",
        "expr-coro",
        "We’re going to hang out",
        "Vamos a reunirnos",
        "Vamos a hacer un coro",
        "Social plan or vibe.",
        "Casual social language.",
        commonSafe,
        ["formal invitations"],
        ["coro"],
        "casual",
        "light",
      ),
      phrase(
        "common-dominican-expressions",
        "expr-mi-amor",
        "What would you like, dear?",
        "¿Qué quiere?",
        "¿Qué tú quieres, mi amor?",
        "Warm service or intimate phrase depending on speaker.",
        "Do not use toward strangers without cultural/relationship context.",
        ["partner", "family", "when said to you by vendor"],
        ["strangers", "coworkers"],
        ["mi amor"],
        "intimate",
        "none",
      ),
    ],
    flashcards: [
      { front: "Vaina", back: "Thing / situation / issue depending on context" },
      { front: "Jevi", back: "Cool / good" },
      { front: "Coro", back: "Hangout / social plan" },
      { front: "Tigre", back: "Street-smart guy; tone-sensitive" },
      { front: "Mi amor", back: "Dear/love; context-sensitive" },
    ],
    dialogue: [
      { speaker: "A", text: "¿Qué lo qué, mano?", translation: "What’s up, bro?" },
      {
        speaker: "B",
        text: "Ta to. Vamos a hacer un coro esta noche.",
        translation: "All good. We’re going to hang out tonight.",
      },
      { speaker: "A", text: "Jevi.", translation: "Cool." },
    ],
    practicePrompts: [
      "Choose which expressions are safe with a professor.",
      "Explain vaina in two contexts.",
      "Decide when mi amor is risky.",
    ],
    quickQuiz: {
      prompt: "Why should learners be careful with tigre?",
      options: ["It only means tiger", "Tone can be playful or negative", "It is formal"],
      answer: "Tone can be playful or negative",
      explanation: "Calling someone tigre requires relationship and tone awareness.",
    },
    relatedDictionaryTerms: [
      "que-lo-que",
      "vaina",
      "jevi",
      "coro",
      "tigre",
      "chin",
      "guagua",
      "concho",
      "dime-a-ve",
      "ta-to",
      "mano",
      "loco",
      "mi-amor",
    ],
  },
];

export const starterContent = {
  lessons,
  dictionary,
};

export const dialects = [
  "dominican",
  "puerto_rican",
  "cuban",
  "mexican",
  "colombian",
  "venezuelan",
  "argentine",
  "chilean",
  "spain",
] as const;
